/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.Factura;
import Clases.Usuario;
import Estructuras.ArbolB_Facturas;
import Estructuras.ArbolB_Viajes;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author juan333
 */
public class InterfazPago extends javax.swing.JFrame {

    
    public ArbolB_Viajes arbol_viajes;
    public ArbolB_Facturas arbol_facturas;
    int id_pago;
    int id_viaje;
    int id_usuario;
    int id_conductor;
    String fecha_;
    double precio_;
    
    
    /**
     * Creates new form InterfazPago
     * @param u
     * @param c
     * @param precio
     * @param a_viajes
     * @param a_fac
     */
    public InterfazPago(Usuario u, Usuario c, double precio, ArbolB_Viajes a_viajes, ArbolB_Facturas a_fac) {
        initComponents();
        setResizable(false);
        setTitle("Realizar pago");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        
        arbol_facturas = a_fac;
        
        id_usuario = u.getId();
        id_conductor = c.getId();
        precio_ = precio;
        
        txt_conductor.setEditable(false);
        txt_usuario.setEditable(false);
        txt_fecha.setEditable(false);
        txt_precio.setEditable(false);
        
        
        txt_usuario.setText(u.getNombre_completo());
        txt_conductor.setText(c.getNombre_completo());
        txt_precio.setText(String.valueOf(precio));

        // Fecha de la transacción
        Date myDate = new Date();
        txt_fecha.setText(new SimpleDateFormat("dd-MM-yyyy").format(myDate));
        fecha_ = txt_fecha.getText();
        precio_ = Double.parseDouble(txt_precio.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txt_usuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txt_conductor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txt_fecha = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txt_precio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_vermapa = new javax.swing.JButton();
        btn_pagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(33, 45, 62));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Gotham Thin", 0, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" Realizar pago");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 351, 53));

        jSeparator1.setBackground(new java.awt.Color(73, 181, 172));
        jSeparator1.setForeground(new java.awt.Color(73, 181, 172));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 310, 10));

        txt_usuario.setEditable(false);
        txt_usuario.setBackground(new java.awt.Color(33, 45, 62));
        txt_usuario.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txt_usuario.setForeground(new java.awt.Color(73, 181, 172));
        txt_usuario.setBorder(null);
        txt_usuario.setCaretColor(new java.awt.Color(73, 181, 172));
        jPanel1.add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 310, 40));

        jLabel4.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("USUARIO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(73, 181, 172));
        jSeparator2.setForeground(new java.awt.Color(73, 181, 172));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 310, 10));

        txt_conductor.setEditable(false);
        txt_conductor.setBackground(new java.awt.Color(33, 45, 62));
        txt_conductor.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txt_conductor.setForeground(new java.awt.Color(73, 181, 172));
        txt_conductor.setBorder(null);
        txt_conductor.setCaretColor(new java.awt.Color(73, 181, 172));
        jPanel1.add(txt_conductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 310, 40));

        jLabel5.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CONDUCTOR");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(73, 181, 172));
        jSeparator3.setForeground(new java.awt.Color(73, 181, 172));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 310, 10));

        txt_fecha.setEditable(false);
        txt_fecha.setBackground(new java.awt.Color(33, 45, 62));
        txt_fecha.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txt_fecha.setForeground(new java.awt.Color(73, 181, 172));
        txt_fecha.setBorder(null);
        txt_fecha.setCaretColor(new java.awt.Color(73, 181, 172));
        jPanel1.add(txt_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 310, 40));

        jLabel6.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("FECHA");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jSeparator4.setBackground(new java.awt.Color(73, 181, 172));
        jSeparator4.setForeground(new java.awt.Color(73, 181, 172));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 310, 10));

        txt_precio.setEditable(false);
        txt_precio.setBackground(new java.awt.Color(33, 45, 62));
        txt_precio.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txt_precio.setForeground(new java.awt.Color(73, 181, 172));
        txt_precio.setBorder(null);
        txt_precio.setCaretColor(new java.awt.Color(73, 181, 172));
        jPanel1.add(txt_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 310, 40));

        jLabel7.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PRECIO");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        btn_vermapa.setBackground(new java.awt.Color(51, 153, 255));
        btn_vermapa.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        btn_vermapa.setText("Ver mapa");
        btn_vermapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vermapaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_vermapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, 120, -1));

        btn_pagar.setBackground(new java.awt.Color(51, 153, 255));
        btn_pagar.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        btn_pagar.setText("Realizar pago");
        btn_pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pagarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_pagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_vermapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vermapaActionPerformed

    }//GEN-LAST:event_btn_vermapaActionPerformed

    private void btn_pagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pagarActionPerformed
        
        //Insertar la factura
        
        arbol_facturas.agregarFactura(new Factura(arbol_facturas.getId_viaje(), id_usuario, id_conductor, id_viaje, fecha_, (int) precio_));
        JOptionPane.showMessageDialog(null, "Factura pagada.");
        
    }//GEN-LAST:event_btn_pagarActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(InterfazPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(InterfazPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(InterfazPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(InterfazPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new InterfazPago().setVisible(truebtn_pagar           
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_pagar;
    private javax.swing.JButton btn_vermapa;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField txt_conductor;
    private javax.swing.JTextField txt_fecha;
    private javax.swing.JTextField txt_precio;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
