/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author juan333
 */
public class ModuloReportes extends javax.swing.JFrame {

    /**
     * Creates new form ModuloReportes
     */
    public ModuloReportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        calcularRuta = new javax.swing.JButton();
        calcularRuta1 = new javax.swing.JButton();
        calcularRuta2 = new javax.swing.JButton();
        calcularRuta3 = new javax.swing.JButton();
        calcularRuta4 = new javax.swing.JButton();
        cerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(33, 45, 62));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Gotham Thin", 0, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Reportes");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 270, 53));

        calcularRuta.setBackground(new java.awt.Color(51, 153, 255));
        calcularRuta.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        calcularRuta.setText("Reporte conductores");
        calcularRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularRutaActionPerformed(evt);
            }
        });
        jPanel1.add(calcularRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 210, -1));

        calcularRuta1.setBackground(new java.awt.Color(51, 153, 255));
        calcularRuta1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        calcularRuta1.setText("Reporte usuarios");
        calcularRuta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularRuta1ActionPerformed(evt);
            }
        });
        jPanel1.add(calcularRuta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 210, -1));

        calcularRuta2.setBackground(new java.awt.Color(51, 153, 255));
        calcularRuta2.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        calcularRuta2.setText("Reporte viajes");
        calcularRuta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularRuta2ActionPerformed(evt);
            }
        });
        jPanel1.add(calcularRuta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 210, -1));

        calcularRuta3.setBackground(new java.awt.Color(51, 153, 255));
        calcularRuta3.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        calcularRuta3.setText("Reporte lugares");
        calcularRuta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularRuta3ActionPerformed(evt);
            }
        });
        jPanel1.add(calcularRuta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 210, -1));

        calcularRuta4.setBackground(new java.awt.Color(51, 153, 255));
        calcularRuta4.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        calcularRuta4.setText("Reporte transacciones");
        calcularRuta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularRuta4ActionPerformed(evt);
            }
        });
        jPanel1.add(calcularRuta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 210, -1));

        cerrarSesion.setBackground(new java.awt.Color(255, 51, 51));
        cerrarSesion.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        cerrarSesion.setText("Regresar");
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(cerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 400, 210, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcularRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularRutaActionPerformed

    
    }//GEN-LAST:event_calcularRutaActionPerformed

    private void calcularRuta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularRuta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calcularRuta1ActionPerformed

    private void calcularRuta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularRuta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calcularRuta2ActionPerformed

    private void calcularRuta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularRuta3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calcularRuta3ActionPerformed

    private void calcularRuta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularRuta4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calcularRuta4ActionPerformed

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed

    }//GEN-LAST:event_cerrarSesionActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ModuloReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ModuloReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ModuloReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ModuloReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ModuloReportes().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcularRuta;
    private javax.swing.JButton calcularRuta1;
    private javax.swing.JButton calcularRuta2;
    private javax.swing.JButton calcularRuta3;
    private javax.swing.JButton calcularRuta4;
    private javax.swing.JButton cerrarSesion;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
