/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.Lugar;
import Estructuras.TablaHash;
import Mapa.Mapa;
import com.teamdev.jxmaps.LatLng;
import com.teamdev.jxmaps.MapViewOptions;
import javax.swing.JOptionPane;

/**
 *
 * @author juan333
 */
public class ModuloViajes extends javax.swing.JFrame {

    public static TablaHash hash;

    /**
     * Creates new form ModuloViajes
     */
    public ModuloViajes(TablaHash t) {
        initComponents();
        setTitle("Modulo de viaje");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setResizable(false);

        hash = t;

        // arreglo grande
        if (hash.isBandera()) {
            for (Lugar l : hash.lugares_redimensionado) {

                if (l != null) {

                    LugarInicio.addItem(l.getNombre());
                    LugarFinal.addItem(l.getNombre());
                }
            }
        } else {

            for (Lugar l : hash.arreglo_lugares) {

                if (l != null) {

                    LugarInicio.addItem(l.getNombre());
                    LugarFinal.addItem(l.getNombre());

                }
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        calcularRuta = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        LugarFinal = new javax.swing.JComboBox<>();
        LugarInicio = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txt_nombreConductor = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txt_idConductor = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txt_lugarinicio = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        txt_lugarfinal = new javax.swing.JTextField();
        calcularRuta1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(33, 45, 62));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Gotham Thin", 0, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Solicitar viaje");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 270, 53));

        jLabel4.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Lugar de destino");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 140, 53));

        calcularRuta.setBackground(new java.awt.Color(51, 153, 255));
        calcularRuta.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        calcularRuta.setText("Ver en mapa");
        calcularRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularRutaActionPerformed(evt);
            }
        });
        jPanel1.add(calcularRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, -1));

        jLabel5.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Datos de conductor");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 200, 53));

        jPanel1.add(LugarFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 220, -1));

        jPanel1.add(LugarInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 220, -1));

        jLabel6.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Lugar de inicio");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 140, 53));

        jSeparator1.setBackground(new java.awt.Color(73, 181, 172));
        jSeparator1.setForeground(new java.awt.Color(73, 181, 172));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 200, 10));

        txt_nombreConductor.setBackground(new java.awt.Color(33, 45, 62));
        txt_nombreConductor.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txt_nombreConductor.setForeground(new java.awt.Color(73, 181, 172));
        txt_nombreConductor.setBorder(null);
        txt_nombreConductor.setCaretColor(new java.awt.Color(73, 181, 172));
        jPanel1.add(txt_nombreConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 200, 40));

        jSeparator2.setBackground(new java.awt.Color(73, 181, 172));
        jSeparator2.setForeground(new java.awt.Color(73, 181, 172));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 200, 10));

        txt_idConductor.setBackground(new java.awt.Color(33, 45, 62));
        txt_idConductor.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txt_idConductor.setForeground(new java.awt.Color(73, 181, 172));
        txt_idConductor.setBorder(null);
        txt_idConductor.setCaretColor(new java.awt.Color(73, 181, 172));
        jPanel1.add(txt_idConductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 200, 40));

        jSeparator3.setBackground(new java.awt.Color(73, 181, 172));
        jSeparator3.setForeground(new java.awt.Color(73, 181, 172));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 200, 10));

        txt_lugarinicio.setBackground(new java.awt.Color(33, 45, 62));
        txt_lugarinicio.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txt_lugarinicio.setForeground(new java.awt.Color(73, 181, 172));
        txt_lugarinicio.setBorder(null);
        txt_lugarinicio.setCaretColor(new java.awt.Color(73, 181, 172));
        jPanel1.add(txt_lugarinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 200, 40));

        jSeparator4.setBackground(new java.awt.Color(73, 181, 172));
        jSeparator4.setForeground(new java.awt.Color(73, 181, 172));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 200, 10));

        txt_lugarfinal.setBackground(new java.awt.Color(33, 45, 62));
        txt_lugarfinal.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txt_lugarfinal.setForeground(new java.awt.Color(73, 181, 172));
        txt_lugarfinal.setBorder(null);
        txt_lugarfinal.setCaretColor(new java.awt.Color(73, 181, 172));
        jPanel1.add(txt_lugarfinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 200, 40));

        calcularRuta1.setBackground(new java.awt.Color(51, 153, 255));
        calcularRuta1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        calcularRuta1.setText("Buscar conductor");
        calcularRuta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularRuta1ActionPerformed(evt);
            }
        });
        jPanel1.add(calcularRuta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcularRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularRutaActionPerformed

        String inicio = (String) LugarInicio.getSelectedItem();
        String fin = (String) LugarFinal.getSelectedItem();

        System.out.println("inicio >> " + inicio);
        System.out.println("fin >> " + fin);

        Lugar inicio_ = hash.buscarLugar(inicio);
        Lugar final_ = hash.buscarLugar(fin);

        MapViewOptions options = new MapViewOptions();
        options.importPlaces();
        options.setApiKey("AIzaSyAu_wHDWkQ4oI98SuwtK1pVqKjIJitE_nw");
        Mapa mapa = new Mapa(options);
        mapa.Renderizar(mapa);
        JOptionPane.showMessageDialog(null, "Renderizando mapa...");
        mapa.agregarMarcador(new LatLng(14.537999, -90.581349));
        LatLng c1 = new LatLng(inicio_.getLatitud(), inicio_.getLongitud());
        LatLng c2 = new LatLng(final_.getLatitud(), final_.getLongitud());
        //LatLng c3 = new LatLng(14.541550, -90.584514);

        LatLng[] camino = {c1, c2};
        mapa.agregarGrafo(camino, true);

    }//GEN-LAST:event_calcularRutaActionPerformed

    private void calcularRuta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularRuta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calcularRuta1ActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ModuloViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ModuloViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ModuloViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ModuloViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ModuloViajes().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> LugarFinal;
    private javax.swing.JComboBox<String> LugarInicio;
    private javax.swing.JButton calcularRuta;
    private javax.swing.JButton calcularRuta1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField txt_idConductor;
    private javax.swing.JTextField txt_lugarfinal;
    private javax.swing.JTextField txt_lugarinicio;
    private javax.swing.JTextField txt_nombreConductor;
    // End of variables declaration//GEN-END:variables
}
