/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.Usuario;
import Estructuras.ArbolB_Usuarios;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author juan333
 */
public class Registro extends javax.swing.JFrame {

    ArbolB_Usuarios arbol;
    //ArbolB_Usuarios arbolb_usuarios;

    /**
     * Creates new form Registro
     *
     * @param arbolb_usuarios
     */
    public Registro(ArbolB_Usuarios arbolb_usuarios) {

        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Registrar usuario");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        registrar.setFocusable(false);
        borrarform.setFocusable(false);
        

        if (arbolb_usuarios == null) {

        } else {
            arbol = arbolb_usuarios;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        password = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        username = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        registrar = new javax.swing.JButton();
        correo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        rol = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        regresar = new javax.swing.JButton();
        borrarform = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();
        latitud = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        longitud = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(33, 45, 62));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Gotham Thin", 0, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Registro");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 27, 227, 53));

        nombre.setBackground(new java.awt.Color(33, 45, 62));
        nombre.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        nombre.setForeground(new java.awt.Color(73, 181, 172));
        nombre.setBorder(null);
        nombre.setCaretColor(new java.awt.Color(73, 181, 172));
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 310, 40));

        jSeparator2.setBackground(new java.awt.Color(73, 181, 172));
        jSeparator2.setForeground(new java.awt.Color(73, 181, 172));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 310, 10));

        password.setBackground(new java.awt.Color(33, 45, 62));
        password.setFont(password.getFont().deriveFont(password.getFont().getSize()+7f));
        password.setForeground(new java.awt.Color(73, 181, 172));
        password.setBorder(null);
        password.setCaretColor(new java.awt.Color(73, 181, 172));
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 270, 36));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagees/icons8_Lock_25px.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 48, 42));

        jLabel4.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contraseña");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(73, 181, 172));
        jSeparator3.setForeground(new java.awt.Color(73, 181, 172));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 310, 10));

        jSeparator4.setBackground(new java.awt.Color(73, 181, 172));
        jSeparator4.setForeground(new java.awt.Color(73, 181, 172));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 310, 10));

        username.setBackground(new java.awt.Color(33, 45, 62));
        username.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        username.setForeground(new java.awt.Color(73, 181, 172));
        username.setBorder(null);
        username.setCaretColor(new java.awt.Color(73, 181, 172));
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 310, 40));

        jLabel6.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Usuario");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        registrar.setBackground(new java.awt.Color(51, 205, 50));
        registrar.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        registrar.setText("Registrar");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        jPanel1.add(registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 397, 141, -1));

        correo.setBackground(new java.awt.Color(33, 45, 62));
        correo.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        correo.setForeground(new java.awt.Color(73, 181, 172));
        correo.setBorder(null);
        correo.setCaretColor(new java.awt.Color(73, 181, 172));
        jPanel1.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 197, 310, 40));

        jLabel8.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Correo electronico");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 150, -1, -1));

        jLabel9.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Telefono");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 140, -1));

        telefono.setBackground(new java.awt.Color(33, 45, 62));
        telefono.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        telefono.setForeground(new java.awt.Color(73, 181, 172));
        telefono.setBorder(null);
        telefono.setCaretColor(new java.awt.Color(73, 181, 172));
        jPanel1.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 170, 40));

        jSeparator5.setBackground(new java.awt.Color(73, 181, 172));
        jSeparator5.setForeground(new java.awt.Color(73, 181, 172));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 170, 10));

        jSeparator6.setBackground(new java.awt.Color(73, 181, 172));
        jSeparator6.setForeground(new java.awt.Color(73, 181, 172));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 249, 310, 10));

        jLabel10.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Rol");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "normal", "conductor" }));
        rol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolActionPerformed(evt);
            }
        });
        jPanel1.add(rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 163, -1));

        jLabel11.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Longitud");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, -1, -1));

        id.setBackground(new java.awt.Color(33, 45, 62));
        id.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        id.setForeground(new java.awt.Color(73, 181, 172));
        id.setBorder(null);
        id.setCaretColor(new java.awt.Color(73, 181, 172));
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 70, 101, 40));

        jSeparator7.setBackground(new java.awt.Color(73, 181, 172));
        jSeparator7.setForeground(new java.awt.Color(73, 181, 172));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 122, 101, 10));

        regresar.setBackground(new java.awt.Color(51, 153, 255));
        regresar.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        jPanel1.add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 397, 141, -1));

        borrarform.setBackground(new java.awt.Color(255, 51, 51));
        borrarform.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        borrarform.setText("Limpiar form");
        borrarform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarformActionPerformed(evt);
            }
        });
        jPanel1.add(borrarform, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 450, 141, -1));

        jSeparator8.setBackground(new java.awt.Color(73, 181, 172));
        jSeparator8.setForeground(new java.awt.Color(73, 181, 172));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 101, 10));

        latitud.setBackground(new java.awt.Color(33, 45, 62));
        latitud.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        latitud.setForeground(new java.awt.Color(73, 181, 172));
        latitud.setBorder(null);
        latitud.setCaretColor(new java.awt.Color(73, 181, 172));
        jPanel1.add(latitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 101, 40));

        jSeparator9.setBackground(new java.awt.Color(73, 181, 172));
        jSeparator9.setForeground(new java.awt.Color(73, 181, 172));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 101, 10));

        longitud.setBackground(new java.awt.Color(33, 45, 62));
        longitud.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        longitud.setForeground(new java.awt.Color(73, 181, 172));
        longitud.setBorder(null);
        longitud.setCaretColor(new java.awt.Color(73, 181, 172));
        jPanel1.add(longitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 101, 40));

        jLabel12.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Id.");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 30, -1, -1));

        jLabel13.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Latitud");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        // TODO add your handling code here:

        try {
            String nombre_ = nombre.getText();
            int id_ = Integer.parseInt(id.getText());
            String user = username.getText();
            String correo_ = correo.getText();
            String contrasenia = password.getText();
            String tel = telefono.getText();
            String rol_ = rol.getSelectedItem().toString();

            Usuario insertar = new Usuario(id_, nombre_, user, correo_, contrasenia, tel, rol_);
            insertar.setLatitud(Float.parseFloat(latitud.getText()));
            insertar.setLongitud(Float.parseFloat(longitud.getText()));

            arbol.agregarUsuario(insertar);
            arbol.mostrarUsuarios();
            JOptionPane.showMessageDialog(null, "Usuario ingresado con exito");

        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error: favor llenar los campos vacios");
            System.out.println(e);
        }
    }//GEN-LAST:event_registrarActionPerformed

    private void rolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rolActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        // TODO add your handling code here:
        //DashbordAministrador d = new DashbordAministrador(arbol);
        //d.setVisible(true);
        dispose();
    }//GEN-LAST:event_regresarActionPerformed

    private void borrarformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarformActionPerformed
        // TODO add your handling code here:
        nombre.setText("");
        id.setText("");
        username.setText("");
        correo.setText("");
        password.setText("");
        telefono.setText("");
        //rol.getSelectedItem().toString();
    }//GEN-LAST:event_borrarformActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Registro().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarform;
    private javax.swing.JTextField correo;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField latitud;
    private javax.swing.JTextField longitud;
    private javax.swing.JTextField nombre;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton registrar;
    private javax.swing.JButton regresar;
    private javax.swing.JComboBox<String> rol;
    private javax.swing.JTextField telefono;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
